### ISSUE TITLE
Installation guide ?

### ISSUE THREAD

**Issue by m333w** [Diffylab/Diffy#1]
Hi,

I woud like to try this project, how i can install it ? And can i run it behind a reverse proxy nginx ?

Best regards.

**Comment by aabbfive** [comment]
You can try a demo https://diffyapp.herokuapp.com/app/index.html
The demo is slightly more advanced than the git I will take over the project and update everything.
In this project there are still 2/3 functions to create/improve.
Sending the magnet torrent and basetime by adding an owner system in the room.
A faster decoding system for larger files.
Thanks.

**Comment by ElTomat** [comment]
Project dead ?

**Comment by aabbfive** [comment]
No just not updated on the main branch, I will do an update soon with a 100% functional version

**Comment by sxiii** [comment]
Any updates? Would be cool to see

**Comment by aabbdev** [comment]
I'm working in a company right now and I have some very big projects I could try to dedicate some time for a remake in several months
