### ISSUE TITLE
Why can't i choose movie?

### ISSUE THREAD

**Issue by Thiasap** [Diffylab/Diffy#2]
`$("#choosemovie").click` in runtime.js is null.
when i click "Choose a movie", there is nothing
after i click Browse and choose a movie, nothing is changed
after i input the magnet, nothing is changed

**Comment by aabbfive** [comment]
I don't have implemented public store ^^

**Comment by aabbfive** [comment]
We need to implement market with api like ipfs/YTS or somethings like this

**Comment by Closty** [comment]
what do u mean? it can't use even now?

**Comment by aabbdev** [comment]
1/3 of the code has been removed, if really interested I could rewrite the application.
